name: EconomyBooster
version: "${project.version}"
main: br.com.aguiarltda.economybooster.EconomyBooster
api-version: "1.20"
depend: [Vault]
commands:
  display:
    description: This command display particles to the players head
    usage: /display <number_of_particles>
  heal:
    description: This command will heal you by the cost of $10 per HP
  config:

  bossbar:

